In [153]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as ms
import sklearn 

#DATA MODELLING

In [154]:
train=pd.read_csv("train_2v.csv")
test=pd.read_csv("test_2v.csv")

In [155]:
train.head()

id  gender   age  hypertension  heart_disease ever_married  \
0  30669    Male   3.0             0              0           No   
1  30468    Male  58.0             1              0          Yes   
2  16523  Female   8.0             0              0           No   
3  56543  Female  70.0             0              0          Yes   
4  46136    Male  14.0             0              0           No   

      work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0      children          Rural              95.12  18.0              NaN   
1       Private          Urban              87.96  39.2     never smoked   
2       Private          Urban             110.89  17.6              NaN   
3       Private          Rural              69.04  35.9  formerly smoked   
4  Never_worked          Rural             161.28  19.1              NaN   

   stroke  
0       0  
1       0  
2       0  
3       0  
4       0

In [156]:
train.head()

id  gender   age  hypertension  heart_disease ever_married  \
0  30669    Male   3.0             0              0           No   
1  30468    Male  58.0             1              0          Yes   
2  16523  Female   8.0             0              0           No   
3  56543  Female  70.0             0              0          Yes   
4  46136    Male  14.0             0              0           No   

      work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0      children          Rural              95.12  18.0              NaN   
1       Private          Urban              87.96  39.2     never smoked   
2       Private          Urban             110.89  17.6              NaN   
3       Private          Rural              69.04  35.9  formerly smoked   
4  Never_worked          Rural             161.28  19.1              NaN   

   stroke  
0       0  
1       0  
2       0  
3       0  
4       0

In [157]:
train.tail()

id  gender   age  hypertension  heart_disease ever_married  \
43395  56196  Female  10.0             0              0           No   
43396   5450  Female  56.0             0              0          Yes   
43397  28375  Female  82.0             1              0          Yes   
43398  27973    Male  40.0             0              0          Yes   
43399  36271  Female  82.0             0              0          Yes   

      work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
43395  children          Urban              58.64  20.4     never smoked   
43396  Govt_job          Urban             213.61  55.4  formerly smoked   
43397   Private          Urban              91.94  28.9  formerly smoked   
43398   Private          Urban              99.16  33.2     never smoked   
43399   Private          Urban              79.48  20.6     never smoked   

       stroke  
43395       0  
43396       0  
43397       0  
43398       0  
43399       0

In [158]:
test.tail()

id  gender   age  hypertension  heart_disease ever_married  \
18596  67353    Male  20.0             0              0           No   
18597    362    Male  61.0             0              0          Yes   
18598  29839  Female  79.0             0              0          Yes   
18599   6438    Male  55.0             0              0          Yes   
18600  16770  Female  38.0             0              0           No   

      work_type Residence_type  avg_glucose_level   bmi   smoking_status  
18596   Private          Rural              74.43  18.4  formerly smoked  
18597  Govt_job          Rural             211.55  31.6           smokes  
18598   Private          Rural             125.74  29.4     never smoked  
18599  Govt_job          Rural              69.46  33.8     never smoked  
18600   Private          Rural              91.23  24.4              NaN

**# lets start MODELLING**

In [213]:
# first start by usining train test split 

In [214]:
from sklearn.model_selection import train_test_split

In [215]:
x_train,x_test,y_train,y_test=train_test_split(x_train,y_train)

In [216]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(21804, 11)
(7268, 11)
(21804,)
(7268,)


In [217]:
x_train.head()

gender  ever_married  work_type  Residence_type  smoking_status     id  \
40691       0             1          2               1               1  64822   
26113       1             1          3               0               1  72243   
26563       0             0          0               1               1  44082   
34339       0             1          2               0               1  12072   
21936       0             1          0               0               1   9334   

        age  hypertension  heart_disease  avg_glucose_level   bmi  
40691  79.0             0              0              64.20  30.6  
26113  44.0             0              0              74.90  29.8  
26563  55.0             0              0             109.58  31.2  
34339  57.0             0              0             183.49  44.1  
21936  77.0             0              1             226.82  25.6

In [218]:
y_train.head()

40691    1
26113    0
26563    0
34339    0
21936    0
Name: stroke, dtype: int64

In [219]:
# here comes the algoritm fitting part let firsty use naive byes classification algo based in gaussian nb

In [220]:
x_test.head()

gender  ever_married  work_type  Residence_type  smoking_status     id  \
30598       0             1          2               0               2   8943   
12919       0             1          0               0               1  61137   
23215       0             1          2               0               2  51654   
17798       0             1          2               1               0  51998   
16679       1             0          2               1               2  17456   

        age  hypertension  heart_disease  avg_glucose_level   bmi  
30598  26.0             0              0              88.85  20.2  
12919  74.0             0              0              63.26  26.8  
23215  50.0             0              0              58.32  31.6  
17798  33.0             0              0             117.34  33.8  
16679  24.0             0              0             105.69  30.2

In [221]:
y_test.head()

30598    0
12919    0
23215    0
17798    0
16679    0
Name: stroke, dtype: int64

In [222]:
from sklearn.naive_bayes import GaussianNB

In [223]:
model=GaussianNB()

In [224]:
model.fit(x_train,y_train)

GaussianNB()

In [225]:
predict=model.predict(x_test)
predict

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [226]:
# lets see the test score of the gaussian nb

In [227]:
test_score=model.score(x_test,y_test)
print("NB TEST SCORE:",test_score)

NB TEST SCORE: 0.9772977435332967


# LEST SEE THE CONFUSION MATRIX 

In [228]:
nb_conf_mtr=pd.crosstab(y_test,predict)
nb_conf_mtr

col_0      0   1
stroke          
0       7094  40
1        125   9

In [229]:
# lets have complete report for naive bayes model 

In [230]:
from sklearn.metrics import classification_report

In [231]:
nbreport=classification_report(y_test,predict)
print(nbreport)

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      7134
           1       0.18      0.07      0.10       134

    accuracy                           0.98      7268
   macro avg       0.58      0.53      0.54      7268
weighted avg       0.97      0.98      0.97      7268



#DECISION TREE MODELLING 

In [232]:
from sklearn.tree import DecisionTreeClassifier

In [233]:
dt_mod=DecisionTreeClassifier()
dt_mod.fit(x_train,y_train)

DecisionTreeClassifier()

In [234]:
y_predict=dt_mod.predict(x_test)
y_predict

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [235]:
# lest see accuracy score

In [236]:
ts_dt_score=dt_mod.score(x_test,y_test)
print(" decision tree classifier score:",ts_dt_score)

 decision tree classifier score: 0.9640891579526693


In [237]:
# lets have confusion matrix 

In [238]:
dt_conf_mtr=pd.crosstab(y_test,y_predict)
dt_conf_mtr

col_0      0    1
stroke           
0       6994  140
1        121   13

In [239]:
# decision tree classification report 

In [240]:
dectree_report=classification_report(y_test,y_predict)
print(dectree_report)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      7134
           1       0.08      0.10      0.09       134

    accuracy                           0.96      7268
   macro avg       0.53      0.54      0.54      7268
weighted avg       0.97      0.96      0.97      7268



RANDOM FOREST

In [241]:
from sklearn.ensemble import RandomForestClassifier

In [242]:
rfc=RandomForestClassifier(n_estimators=100)

In [243]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [244]:
y_pred_rfc=rfc.predict(x_test)

In [245]:
# lets ahve confusion matrix 

In [246]:
print(pd.crosstab(y_test,y_pred_rfc))

col_0      0
stroke      
0       7134
1        134


In [247]:
import warnings
warnings.filterwarnings("ignore")
print(classification_report(y_test,y_pred_rfc))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      7134
           1       0.00      0.00      0.00       134

    accuracy                           0.98      7268
   macro avg       0.49      0.50      0.50      7268
weighted avg       0.96      0.98      0.97      7268



In [290]:
rfc_score=rfc.score(x_test,y_test)
rfc_score

0.9998165474224913

# lets do it with MLPC CLASSIFIER 

In [249]:
from sklearn.neural_network import MLPClassifier

In [250]:
mlp=MLPClassifier()

In [251]:
mlp.fit(x_train,y_train)

MLPClassifier()

In [252]:
y_pred_mlp=mlp.predict(x_test)
y_pred_mlp

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [292]:
mlp_score=mlp.score(x_test,y_test)
mlp_score

0.9809209319390938

In [254]:
# lets cross validating the accuracies by using cross validation score

In [255]:
from sklearn.model_selection import cross_val_score

In [256]:
# cv for gaussianb

In [257]:
cross_val_score(model,x_train,y_train,cv = 20, scoring='accuracy').mean()

0.975967969794566

In [258]:
#cv for decision_tree

In [259]:
cross_val_score(dt_mod,x_train,y_train,cv=20,scoring="accuracy").mean()

0.9596405536541679

In [260]:
#cross val score for random forest classifier

In [261]:
cross_val_score(rfc,x_train,y_train,cv=20,scoring="accuracy").mean()

0.9810127061277004

In [262]:
# cross val score of mlp classifier 

In [263]:
cross_val_score(mlp,x_train,y_train,cv=20,scoring="accuracy").mean()

0.9799577863924183

APPLYING PCA (PRINCIPAL COMPONENT ANALYSIS)

In [264]:
from sklearn.decomposition import PCA

In [265]:
pca=PCA(n_components=3)

In [266]:
principalComponents=pca.fit_transform(x_train)

In [267]:
from sklearn.model_selection import train_test_split

In [268]:
x_train,x_test,y_train,y_test=train_test_split(x_train,y_train)

In [269]:
model_2=GaussianNB()

In [270]:
model_2.fit(x_train,y_train)

GaussianNB()

In [271]:
test_score_1=model_2.score(x_test,y_test)
print("test score after pca",test_score_1)

test score after pca 0.9745000917262887


In [272]:
# decision tree classifier after pca

In [273]:
dt_mod2=DecisionTreeClassifier()

In [274]:
dt_mod2.fit(x_train,y_train)

DecisionTreeClassifier()

In [275]:
ts_dt_score2=dt_mod2.score(x_test,y_test)
print(" score after pcs in dt:",ts_dt_score2)

 score after pcs in dt: 0.9607411484131352


In [276]:
# new model random forest classifier after pca

In [277]:
rfc1=RandomForestClassifier(n_estimators=100)

In [278]:
rfc1.fit(x_train,y_train)

RandomForestClassifier()

In [279]:
y_pred_rfc1=rfc1.predict(x_test)
y_pred_rfc1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [280]:
print(pd.crosstab(y_test,y_pred_rfc1))

col_0      0
stroke      
0       5348
1        103


In [296]:
rfc1_score=rfc1.score(x_test,y_test)
rfc1_score

0.9811043845166024

In [298]:
mlp1=MLPClassifier()
mlp1.fit(x_train,y_train)
y_pred_mlp1=mlp1.predict(x_test)
mlp1_score=mlp1.score(x_test,y_test)
mlp1_score

0.979453311319024

In [283]:
# lest claculate cross validation score for each model after pca

In [284]:
cross_val_score(model_2,x_train,y_train,cv=20,scoring="accuracy").mean()

0.9750502763704052

In [285]:
cross_val_score(dt_mod2,x_train,y_train,cv=20,scoring="accuracy").mean()

0.9603125663992245

In [286]:
cross_val_score(rfc1,x_train,y_train,cv=20,scoring="accuracy").mean()

0.9809823643660239

In [287]:
cross_val_score(mlp1,x_train,y_train,cv=20,scoring="accuracy").mean()

0.9808599653452161

In [300]:
x=pd.DataFrame([test_score,ts_dt_score,rfc_score,mlp_score,"SCORE AFTER PCA",test_score_1,ts_dt_score2,rfc1_score,mlp1_score])
print(x,end=" ")

                 0
0         0.977298
1         0.964089
2         0.999817
3         0.980921
4  SCORE AFTER PCA
5           0.9745
6         0.960741
7         0.981104
8         0.979453 